### ISSUE TITLE
glViewport issues with Retina display on macOS

### ISSUE THREAD

**Issue by zinwalin** [wiranoid/breakout#4]
![image](https://user-images.githubusercontent.com/5416196/81533960-b8ec6180-9399-11ea-8d5e-c36b9b45b828.png)

![image](https://user-images.githubusercontent.com/5416196/81533941-af62f980-9399-11ea-8f13-90b3d7ab59a6.png)

**Comment by zinwalin** [comment]
If I change width and height with half value. it shows incorrectly as well.

![image](https://user-images.githubusercontent.com/5416196/81534107-0b2d8280-939a-11ea-8e20-149337c9b1bc.png)


![image](https://user-images.githubusercontent.com/5416196/81534080-f9e47600-9399-11ea-9d89-db15afd873db.png)

**Comment by maltekliemann** [comment]
@zinwalin Pull request #5 fixes this issue (in addition to adding macOS support). Summary:

* You're correct that the default framebuffer's width and height must be doubled, although it is better to use `glfwGetFramebufferSize` instead of hard-coding the scaling factor
* The off-screen framebuffers (in the `PostProcessor`) must also be adapted to the default framebuffer's size
* Care must be taken when the window is moved between displays with different scaling (tear down and setup the framebuffers everytime)

**Comment by sdavydouski** [comment]
Fixed in #5 by @maltekliemann 
Thank you!

**Comment by zinwalin** [comment]
> @zinwalin Pull request #5 fixes this issue (in addition to adding macOS support). Summary:
> 
> * You're correct that the default framebuffer's width and height must be doubled, although it is better to use `glfwGetFramebufferSize` instead of hard-coding the scaling factor
> * The off-screen framebuffers (in the `PostProcessor`) must also be adapted to the default framebuffer's size
> * Care must be taken when the window is moved between displays with different scaling (tear down and setup the framebuffers everytime)

thanks heaps
